In [ ]:
import pandas as pd
df = pd.read_csv('/content/enem_simulado_brasil.csv')
df.head()

,id_estudante,estado,cidade,tipo_escola,renda_familiar,nota_matematica,nota_linguagens,nota_ciencias,nota_humanas,nota_redacao,media_final
0,1,RJ,Rio de Janeiro,Privada,4277.46,595.34,648.40,699.21,675.79,682.02,660.15
1,2,AM,Manaus,Privada,10758.81,788.20,797.79,648.60,759.84,795.12,757.91
2,3,BA,Feira de Santana,Pública,11641.62,730.29,636.45,704.96,721.38,685.06,695.63
3,4,RJ,Duque de Caxias,Pública,4963.13,391.00,493.05,508.04,434.84,375.36,440.46
4,5,RJ,Niterói,Privada,6197.79,452.66,576.27,476.36,426.11,601.69,506.62

In [ ]:
print("dimensões da base (linhas, colunas: )", df.shape)
print("\n Nomes das colunas:")
print(df.columns.tolist())

dimensões da base (linhas, colunas: ) (1000, 11)

 Nomes das colunas:
['id_estudante', 'estado', 'cidade', 'tipo_escola', 'renda_familiar', 'nota_matematica', 'nota_linguagens', 'nota_ciencias', 'nota_humanas', 'nota_redacao', 'media_final']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_estudante     1000 non-null   int64
 1   estado           1000 non-null   object
 2   cidade           1000 non-null   object
 3   tipo_escola      1000 non-null   object
 4   renda_familiar   1000 non-null   float64
 5   nota_matematica  1000 non-null   float64
 6   nota_linguagens  1000 non-null   float64
 7   nota_ciencias    1000 non-null   float64
 8   nota_humanas     1000 non-null   float64
 9   nota_redacao     1000 non-null   float64
 10  media_final      1000 non-null   float64
dtypes: float64(7), int64(1), object(3)
memory usage: 86.1+ KB

In [ ]:
df.describe()

,id_estudante,renda_familiar,nota_matematica,nota_linguagens,nota_ciencias,nota_humanas,nota_redacao,media_final
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,7799.798130,627.174810,603.825560,609.070630,607.896080,608.490160,611.291390
std,288.819436,4037.570969,106.486573,99.613751,103.406035,100.448405,111.919292,87.391626
min,1.000000,825.530000,278.750000,309.340000,259.270000,259.630000,202.550000,310.960000
25%,250.750000,4315.197500,555.965000,536.865000,537.460000,539.320000,535.797500,548.915000
50%,500.500000,7982.145000,622.975000,603.400000,612.775000,609.820000,608.275000,613.875000
75%,750.250000,11269.510000,695.195000,669.335000,677.657500,676.132500,683.815000,671.775000
max,1000.000000,14972.860000,968.430000,1000.000000,966.940000,1000.000000,968.230000,947.770000

In [ ]:
df.isnull().sum()

id_estudante       0
estado             0
cidade             0
tipo_escola        0
renda_familiar     0
nota_matematica    0
nota_linguagens    0
nota_ciencias      0
nota_humanas       0
nota_redacao       0
media_final        0
dtype: int64